services:
    bibl.book.service.abstract:
        class: BookBundle\Service\AbstractService
        arguments:
        - @doctrine.orm.entity_manager

    bibl.book.service.book:
        class: BookBundle\Service\BookService
        parent: bibl.book.service.abstract

    bibl.book.service.category:
        class: BookBundle\Service\CategoryService
        parent: bibl.book.service.abstract

    bibl.book.service.member:
        class: BookBundle\Service\MemberService
        parent: bibl.book.service.abstract
