api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

book:
    resource: "@BookBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
